-- MySQL Script generated by MySQL Workbench
-- Sat May  7 16:21:08 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- Schema cert_dev
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cert_test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cert_dev` DEFAULT CHARACTER SET utf8;

-- -----------------------------------------------------
-- Table `cert_dev`.`gift_certificate`
-- -----------------------------------------------------

